---
AWSTemplateFormatVersion: 2010-09-09
Description: Provides the infrastructure that supports the IAPP Utility Portal
Parameters:
  pOrganization:
    Description: The name of the portfolio that identifies its products, applications, and components
    Type: String
    MinLength: 1
    MaxLength: 30
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.organization }}
  pPortfolio:
    Description: The name of the portfolio that identifies its products, applications, and components
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.portfolio }}
  pProduct:
    Description: The name of the product that identifies its applications and components
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.product }}
  pApplication:
    Description: The name of the application (or service module) that identifies its components
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.application }}
  pComponent:
    Description: The name of the component that aligns with the application or service module
    Type: String
    MinLength: 0
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.component }}
  pDepartment:
    Description: The name of the department that owns the resource
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.department }}
  pEnvironment:
    Description: 'The name of the environment in which the resource is running (e.g.: sandbox, development, test, production)'
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.aws.environment }}
  pSupportEmail:
    Description: The email address of the support team to contact
    Type: String
    MinLength: 8
    MaxLength: 30
    AllowedPattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
    Default: ${{ iapp.catalog.support_email }}
  pSourceCodeURL:
    Description: The location where the source code resides
    Type: String 
    Default: ${{ iapp.code.sourcecode_url }}
  pUserPoolId:
    Description: 'The id of the Cognito User Pool to authenticate the application' 
    Type: String 
    Default: 'us-east-1_xnWubxCLi'
  pDomainName:
    Description: Domain name
    Default: ''
    Type: String
  pAcmCertArn:
    Description: Acm Certificate Arn
    Default: 'arn:aws:acm:us-east-1:298049552655:certificate/d6bc89eb-dc5c-42f3-b285-450b3926be01'
    Type: String
Conditions:
  HasCustomDomainName:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: pDomainName
Resources:  
  rS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Metadata:
      Comment: 'Bucket to store the web portal content'
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      BucketName: 
        !Sub ${pOrganization}-${pApplication}-${pEnvironment}-portal
      Tags: 
        - 
          Key: "Name"
          Value:
            !Sub ${pApplication}-${pEnvironment}-portal
        - 
          Key: "iapp-organization"
          Value: 
            !Ref pOrganization
        - 
          Key: "iapp-portfolio"
          Value: 
            !Ref pPortfolio
        - 
          Key: "iapp-product"
          Value: 
            !Ref pProduct
        - 
          Key: "iapp-application"
          Value: 
            !Ref pApplication
        - 
          Key: "iapp-component"
          Value:
            !Ref pComponent
        - 
          Key: "iapp-department"
          Value:
            !Ref pDepartment
        - 
          Key: "iapp-environment"
          Value:
            !Ref pEnvironment
        - 
          Key: "iapp-support-email"
          Value:
            !Ref pSupportEmail    
        - 
          Key: "iapp-access-type"
          Value: 'private'
        - 
          Key: "iapp-resource-type"
          Value: 'data'
  rCfOriginAccessIdentity:    
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'   
    Metadata:
      Comment: 'Access S3 bucket content only through CloudFront'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access S3 bucket content only through CloudFront'
  rS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - rS3Bucket
      - rCfOriginAccessIdentity
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the data'
    Properties:
      Bucket: !Ref rS3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt rCfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${rS3Bucket}/*'
  rCfDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: 'A distribution for the IAPP Utility Portal used for various internal-use applications'
        Aliases:
        - Fn::If:
          - HasCustomDomainName
          - !Sub "${pEnvironment}-${pDomainName}"
          - Ref: AWS::NoValue
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: !Sub 's3-origin-${rS3Bucket}'
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        Origins:
          - DomainName: !GetAtt rS3Bucket.DomainName
            Id: !Sub 's3-origin-${rS3Bucket}'
            OriginPath: ''
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${rCfOriginAccessIdentity}'
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn:
            Fn::If:
            - HasCustomDomainName
            - Ref: pAcmCertArn
            - Ref: AWS::NoValue
          CloudFrontDefaultCertificate:
            Fn::If:
            - HasCustomDomainName
            - Ref: AWS::NoValue
            - true
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod:
            Fn::If:
            - HasCustomDomainName
            - sni-only
            - Ref: AWS::NoValue
Outputs:
  PortalContentBucket:
    Description: 'Web Content S3 Bucket name'
    Value: !Ref rS3Bucket
  CfDistributionId:
    Description: 'Id for our cloudfront distribution'
    Value: !Ref rCfDistribution
  CfDistributionDomainName:
    Description: 'Domain name for our cloudfront distribution'
    Value: !GetAtt rCfDistribution.DomainName